apiVersion: v1
kind: ReplicationController
metadata: 
  name: kuard-rc
  labels: 
    env: dev
spec:
  replicas: 1
  selector:
    app: kuard-rc-app
  template:
    metadata:
      labels:
        app: kuard-rc-app
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
        ports: 
        - containerPort: 8080
          name: http
          protocol: TCP
      nodeSelector: 
        env: dev
